# Generated by Django 5.2.5 on 2025-09-01 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], default='Other', max_length=100)),
                ('published_at', models.DateTimeField(null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
